/**:
  user_command_node:
    ros__parameters:
      server_ip: "192.168.19.101"
      server_port: 8888
      client_port: 9999
      fsm_mode: "transform_up"     # 初始状态机模式，可选值: transform_up, idle, transform_down, loco, joint_pd, car, rl_1, rl_2, rl_3
      # 姿态控制参数（仅在 loco 状态下有效）
      pose_frame_id: "world"        # 坐标系名称
      pose_position_z: 0.2          # 位置 z (米)，范围 0.1 到 0.3，仅 z 有效
      pose_orientation_x: 0.0       # 四元数 x
      pose_orientation_y: 0.171    # 四元数 y
      pose_orientation_z: 0.0       # 四元数 z
      pose_orientation_w: 0.985    # 四元数 w
      
